name: 'Oura Profile Cards'
description: 'Generates SVG cards from your Oura data.'
author: 'savvan0h'
inputs:
  OURA_API_TOKEN:
    description: 'Your personal Oura API token.'
    required: true
runs:
  using: 'node20'
  main: 'src/index.js'
